optimizer:
  name: adam
  lr: 1.0e-3
  weight_decay: 0

train:
  epoch: 100
  batch_size: 4096
  save_model: true
  loss: pairwise
  log_loss: false
  test_step: 3
  patience: 5
  reproducible: true
  seed: 42
  trainer: autocf_trainer

test:
  metrics: [mrr, recall, ndcg]
  k: [5, 10, 20, 40]
  batch_size: 4096

data:
  type: general_cf
  name: huggingface

model:
  name: autocf
  keep_rate: 0.2
  gcn_layer: 2
  gt_layer: 2
  reg_weight: 1.0e-8
  embedding_size: 64
  head_num: 4
  ssl_reg: 1
  seed_num: 100
  mask_depth: 2
  fix_steps: 10

tune:
  enable: true
  hyperparameters: [lr, gcn_layer]
  lr: [1.0e-3, 1.0e-4, 1.0e-5]
  gcn_layer: [2, 3]