optimizer:
  name: adam
  lr: 1.0e-3
  weight_decay: 0

train:
  epoch: 100
  batch_size: 4096
  save_model: false
  loss: pairwise
  log_loss: false
  test_step: 3
  patience: 5
  reproducible: true
  seed: 42

test:
  metrics: [mrr, recall, ndcg]
  k: [5, 10, 20, 40]
  batch_size: 4096

data:
  type: general_cf
  name: huggingface

model:
  name: hccf
  keep_rate: 0.5
  layer_num: 2
  reg_weight: 1.0e-8
  cl_weight: 1.0e-2
  temperature: 0.1
  embedding_size: 64
  mult: 1.0
  hyper_num: 128
  leaky: 1.0

tune:
  enable: true
  hyperparameters: [lr, layer_num]
  lr: [1.0e-3, 1.0e-4, 1.0e-5]
  layer_num: [2, 3]