optimizer:
  name: adam
  lr: 1.0e-4 # not 1e-3
  weight_decay: 0

train:
  trainer: trainer
  epoch: 100
  batch_size: 4096
  save_model: true
  loss: pairwise # bpr
  test_step: 3 # evaluate per {test_step} epochs
  patience: 5
  # pretrain_path: checkpoint/kgrec/kgrec-last-fm-1689594554.pth
  reproducible: true
  seed: 42

test:
  metrics: [mrr, recall, ndcg] # choose in {ndcg, recall, precision, mrr}
  k: [5, 10, 20, 40] # top-k
  batch_size: 1024 # How many users per batch during validation
  eval_at_one_forward: true

data:
  type: kg # choose in {general_cf, multi_behavior, sequential, social, kg}
  name: huggingface

model:
  name: kgrec # case-insensitive
  layer_num: 2
  decay_weight: 1.0e-5
  embedding_size: 64
  node_dropout: true
  node_dropout_rate: 0.5
  mess_dropout: true
  mess_dropout_rate: 0.1

  mae_coef: 0.1
  mae_msize: 256
  cl_coef: 0.001
  tau: 0.2
  cl_drop_ratio: 0.5
  samp_func: torch

tune:
  enable: true
  hyperparameters: [lr, layer_num]
  lr: [1.0e-3]
  layer_num: [2, 3]