optimizer:
  name: adam
  lr: 1.0e-3
  weight_decay: 0

train:
  epoch: 100
  batch_size: 4096
  save_model: true
  loss: pairwise # bpr
  log_loss: false # whether to log loss
  test_step: 3 # evaluate per {test_step} epochs
  patience: 5
  reproducible: true
  seed: 42
  #pretrain_path: ./checkpoint/xxxx.pth

test:
  metrics: [mrr, recall, ndcg]
  k: [5, 10, 20, 40]
  batch_size: 4096

data:
  type: general_cf # choose in {general_cf, multi_behavior, sequential, social}
  name: huggingface


model:
  name: lightgcn # case-insensitive
  keep_rate: 0.5
  layer_num: 2
  reg_weight: 1.0e-8
  embedding_size: 64

tune:
  enable: true
  hyperparameters: [lr, layer_num]
  lr: [1.0e-3, 1.0e-4, 1.0e-5]
  layer_num: [2, 3]

