optimizer:
  name: adam
  lr: 1.0e-3
  weight_decay: 0

train:
  epoch: 100
  batch_size: 4096
  save_model: true
  loss: pairwise # bpr
  test_step: 3 # evaluate per {test_step} epochs
  patience: 5 # early stopping
  #pretrain_path: ./checkpoint/xxxx.pth
  reproducible: true
  seed: 42
  tensorboard: true
  early_stop: true

test:
  metrics: [mrr, recall, ndcg]
  k: [5, 10, 20, 40]
  batch_size: 4096

data:
  type: social # choose in {general_cf, multi_behavior, sequential, social}
  name: huggingface

model:
  name: mhcn # case-insensitive
  layer_num: 2
  reg_weight: 1.0e-3
  embedding_size: 64
  ss_rate: 1.0e-2

tune:
  enable: true
  hyperparameters: [lr, layer_num]
  lr: [1.0e-3, 1.0e-4, 1.0e-5]
  layer_num: [2, 3]
